# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jessica Paoli is an interdisciplinary designer and visual artist.
email: jes@isca.me
author: Jessica Paoli
author_email: jes@sica.me
description: > # this means to ignore newlines until "baseurl:"
  Jessica Paoli is an interdisciplinary designer, illustrator, and
  visual artist in Cleveland, Ohio. This is her sketchbook.
baseurl:      "" # the subpath of your site, e.g. /blog
url:          "" # the base hostname & protocol for your site
locale:       en-US


# Where things are
layouts_dir:  ./_layouts
data_dir:     ./_data
sass_dir:     ./_sass
include:      ["_pages"]
collections:
  sketches:
    output: true
    permalink: /sketchbook/:path/
  blog:
    output: true
    permalink: /blog/:path/

# Handling Reading
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Plugins
whitelist:    []
gems:         []

# Conversion
markdown:     kramdown

# Serving
port:         4000
host:         127.0.0.1

# Outputting
permalink:    "/:title"
